// Generated by CoffeeScript 1.7.1
(function() {
  var chatApp;

  chatApp = angular.module('chatApp', ["firebase"]);

  chatApp.controller("chatController", function($scope, $firebase) {
    var bla, ref;
    ref = new Firebase("https://jamie-and-camilla.firebaseio.com/");
    bla = "SDFds";
    $scope.messages = $firebase(ref);
    return $scope.addMessage = function(e) {
      if (e.keyCode !== 13) {
        return;
      }
      $scope.messages.$add({
        name: $scope.username,
        body: $scope.msg
      });
      return $scope.msg = "";
    };
  });

}).call(this);
